version: 2
jobs:
  build:
    working_directory: ~/golang/src/github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
    parallelism: 1
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      PATH: /usr/local/go/bin:/bin:/usr/bin:/usr/local/bin
      IMPORT_PATH: github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
    docker:
    - image: circleci/golang:latest
    - image: ryankurte/docker-native-dev:latest
    steps:
    - checkout
    - run: echo "export GOPATH=\"$HOME/golang\" PATH=\"$HOME/golang/bin:$PATH\"" >> ~/.bashrc
    - run: /bin/mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - run: go get github.com/golang/lint/golint
    - run: go get github.com/jstemmer/go-junit-report
    - run: go get -t -d -v "$IMPORT_PATH/..."
    # Test
    - run: go vet ./...
    - run: golint -set_exit_status ./...
    - run: ./build/gofmt.sh
    - run: ./build/license.sh
    - run: go build -v "$IMPORT_PATH/..."
    - run: ./build/test-and-coverage.sh
    - run: bash <(curl -s https://codecov.io/bash)
    # Teardown
    #   If you break your build into multiple jobs with workflows, you will probably want to do the parts of this that are relevant in each
    # Save test results
    - store_test_results:
        path: /tmp/circleci-test-results
    # Save artifacts
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results
